print("""
     ____         _      ___    
    |    \       /_\    / _  \   (_)   _____
    |  _   \    /|_|\  | |_| |    _   |     |
    | | |   |  | | | | |  _  |   | |  |     |
    | |_|   |  |  _  | | | \ \   | |  |     |
    |______|   |_| |_| |_|  \_|  |_|  |_____| DarioStar999
""")
totalevoti =  input("Quanti voti hai in totale?Inserisci un numero tra 2 e 50: ")
if totalevoti == "2":
    voto1= input("inserisci il numero del voto: ")
    voto2= input("inserisci il numero del voto: ")
    calcolo1= (int(voto1) + int(voto2))
    calcolo2= (int(calcolo1) / int(totalevoti))
    print(calcolo2)
    input("Da Dario:")
if totalevoti == "3":
    voto1= input("inserisci il numero del voto: ")
    voto2= input("inserisci il numero del voto: ")
    voto3= input("inserisci il numero del voto: ")
    calcolo1= (int(voto1) + int(voto2) + int(voto3))
    calcolo2= (int(calcolo1) / int(totalevoti))
    print(calcolo2)
    input("Da Dario:")
if totalevoti == "4":
    voto1= input("inserisci il numero del voto: ")
    voto2= input("inserisci il numero del voto: ")
    voto3= input("inserisci il numero del voto: ")
    voto4= input("inserisci il numero del voto: ")
    calcolo1= (int(voto1) + int(voto2) + int(voto3) + int(voto4))
    calcolo2= (int(calcolo1) / int(totalevoti))
    print(calcolo2)
    input("Da Dario:")
if totalevoti == "5":
    voto1= input("inserisci il numero del voto: ")
    voto2= input("inserisci il numero del voto: ")
    voto3= input("inserisci il numero del voto: ")
    voto4= input("inserisci il numero del voto: ")
    voto5= input("inserisci il numero del voto: ")
    calcolo1= (int(voto1) + int(voto2) + int(voto3) + int(voto4) + int(voto5))
    calcolo2= (int(calcolo1) / int(totalevoti))
    print(calcolo2)
    input("Da Dario:")
if totalevoti == "6":
    voto1= input("inserisci il numero del voto: ")
    voto2= input("inserisci il numero del voto: ")
    voto3= input("inserisci il numero del voto: ")
    voto4= input("inserisci il numero del voto: ")
    voto5= input("inserisci il numero del voto: ")
    voto6= input("inserisci il numero del voto: ")
    calcolo1= (int(voto1) + int(voto2) + int(voto3) + int(voto4) + int(voto5) + int(voto6))
    calcolo2= (int(calcolo1) / int(totalevoti))
    print(calcolo2)
    input("Da Dario:")
if totalevoti == "7":
    voto1= input("inserisci il numero del voto: ")
    voto2= input("inserisci il numero del voto: ")
    voto3= input("inserisci il numero del voto: ")
    voto4= input("inserisci il numero del voto: ")
    voto5= input("inserisci il numero del voto: ")
    voto6= input("inserisci il numero del voto: ")
    voto7= input("inserisci il numero del voto: ")
    calcolo1= (int(voto1) + int(voto2) + int(voto3) + int(voto4) + int(voto5) + int(voto6) + int(voto7))
    calcolo2= (int(calcolo1) / int(totalevoti))
    print(calcolo2)
    input("Da Dario:")
if totalevoti == "8":
    voto1= input("inserisci il numero del voto: ")
    voto2= input("inserisci il numero del voto: ")
    voto3= input("inserisci il numero del voto: ")
    voto4= input("inserisci il numero del voto: ")
    voto5= input("inserisci il numero del voto: ")
    voto6= input("inserisci il numero del voto: ")
    voto7= input("inserisci il numero del voto: ")
    voto8= input("inserisci il numero del voto: ")
    calcolo1= (int(voto1) + int(voto2) + int(voto3) + int(voto4) + int(voto5) + int(voto6) + int(voto7) + int(voto8))
    calcolo2= (int(calcolo1) / int(totalevoti))
    print(calcolo2)
    input("Da Dario:")
if totalevoti == "9":
    voto1= input("inserisci il numero del voto: ")
    voto2= input("inserisci il numero del voto: ")
    voto3= input("inserisci il numero del voto: ")
    voto4= input("inserisci il numero del voto: ")
    voto5= input("inserisci il numero del voto: ")
    voto6= input("inserisci il numero del voto: ")
    voto7= input("inserisci il numero del voto: ")
    voto8= input("inserisci il numero del voto: ")
    voto9= input("inserisci il numero del voto: ")
    calcolo1= (int(voto1) + int(voto2) + int(voto3) + int(voto4) + int(voto5) + int(voto6) + int(voto7) + int(voto8) + int(voto9))
    calcolo2= (int(calcolo1) / int(totalevoti))
    print(calcolo2)
    input("Da Dario:")
if totalevoti == "10":
    voto1= input("inserisci il numero del voto: ")
    voto2= input("inserisci il numero del voto: ")
    voto3= input("inserisci il numero del voto: ")
    voto4= input("inserisci il numero del voto: ")
    voto5= input("inserisci il numero del voto: ")
    voto6= input("inserisci il numero del voto: ")
    voto7= input("inserisci il numero del voto: ")
    voto8= input("inserisci il numero del voto: ")
    voto9= input("inserisci il numero del voto: ")
    voto10= input("inserisci il numero del voto: ")
    calcolo1= (int(voto1) + int(voto2) + int(voto3) + int(voto4) + int(voto5) + int(voto6) + int(voto7) + int(voto8) + int(voto9) + int(voto10))
    calcolo2= (int(calcolo1) / int(totalevoti))
    print(calcolo2)
    input("Da Dario:")
if totalevoti == "11":
    voto1= input("inserisci il numero del voto: ")
    voto2= input("inserisci il numero del voto: ")
    voto3= input("inserisci il numero del voto: ")
    voto4= input("inserisci il numero del voto: ")
    voto5= input("inserisci il numero del voto: ")
    voto6= input("inserisci il numero del voto: ")
    voto7= input("inserisci il numero del voto: ")
    voto8= input("inserisci il numero del voto: ")
    voto9= input("inserisci il numero del voto: ")
    voto10= input("inserisci il numero del voto: ")
    voto11= input("inserisci il numero del voto: ")
    calcolo1= (int(voto1) + int(voto2) + int(voto3) + int(voto4) + int(voto5) + int(voto6) + int(voto7) + int(voto8) + int(voto9) + int(voto10) + int(voto11))
    calcolo2= (int(calcolo1) / int(totalevoti))
    print(calcolo2)
    input("Da Dario:")
if totalevoti == "12":
    voto1= input("inserisci il numero del voto: ")
    voto2= input("inserisci il numero del voto: ")
    voto3= input("inserisci il numero del voto: ")
    voto4= input("inserisci il numero del voto: ")
    voto5= input("inserisci il numero del voto: ")
    voto6= input("inserisci il numero del voto: ")
    voto7= input("inserisci il numero del voto: ")
    voto8= input("inserisci il numero del voto: ")
    voto9= input("inserisci il numero del voto: ")
    voto10= input("inserisci il numero del voto: ")
    voto11= input("inserisci il numero del voto: ")
    voto12= input("inserisci il numero del voto: ")
    calcolo1= (int(voto1) + int(voto2) + int(voto3) + int(voto4) + int(voto5) + int(voto6) + int(voto7) + int(voto8) + int(voto9) + int(voto10) + int(voto11) + int(voto12))
    calcolo2= (int(calcolo1) / int(totalevoti))
    print(calcolo2)
    input("Da Dario:")
if totalevoti == "13":
    voto1= input("inserisci il numero del voto: ")
    voto2= input("inserisci il numero del voto: ")
    voto3= input("inserisci il numero del voto: ")
    voto4= input("inserisci il numero del voto: ")
    voto5= input("inserisci il numero del voto: ")
    voto6= input("inserisci il numero del voto: ")
    voto7= input("inserisci il numero del voto: ")
    voto8= input("inserisci il numero del voto: ")
    voto9= input("inserisci il numero del voto: ")
    voto10= input("inserisci il numero del voto: ")
    voto11= input("inserisci il numero del voto: ")
    voto12= input("inserisci il numero del voto: ")
    voto13= input("inserisci il numero del voto: ")
    calcolo1= (int(voto1) + int(voto2) + int(voto3) + int(voto4) + int(voto5) + int(voto6) + int(voto7) + int(voto8) + int(voto9) + int(voto10) + int(voto11) + int(voto12) + int(voto13))
    calcolo2= (int(calcolo1) / int(totalevoti))
    print(calcolo2)
    input("Da Dario:")
if totalevoti == "14":
    voto1= input("inserisci il numero del voto: ")
    voto2= input("inserisci il numero del voto: ")
    voto3= input("inserisci il numero del voto: ")
    voto4= input("inserisci il numero del voto: ")
    voto5= input("inserisci il numero del voto: ")
    voto6= input("inserisci il numero del voto: ")
    voto7= input("inserisci il numero del voto: ")
    voto8= input("inserisci il numero del voto: ")
    voto9= input("inserisci il numero del voto: ")
    voto10= input("inserisci il numero del voto: ")
    voto11= input("inserisci il numero del voto: ")
    voto12= input("inserisci il numero del voto: ")
    voto13= input("inserisci il numero del voto: ")
    voto14= input("inserisci il numero del voto: ")
    calcolo1= (int(voto1) + int(voto2) + int(voto3) + int(voto4) + int(voto5) + int(voto6) + int(voto7) + int(voto8) + int(voto9) + int(voto10) + int(voto11) + int(voto12) + int(voto13) + int(voto14))
    calcolo2= (int(calcolo1) / int(totalevoti))
    print(calcolo2)
    input("Da Dario:")
if totalevoti == "15":
    voto1= input("inserisci il numero del voto: ")
    voto2= input("inserisci il numero del voto: ")
    voto3= input("inserisci il numero del voto: ")
    voto4= input("inserisci il numero del voto: ")
    voto5= input("inserisci il numero del voto: ")
    voto6= input("inserisci il numero del voto: ")
    voto7= input("inserisci il numero del voto: ")
    voto8= input("inserisci il numero del voto: ")
    voto9= input("inserisci il numero del voto: ")
    voto10= input("inserisci il numero del voto: ")
    voto11= input("inserisci il numero del voto: ")
    voto12= input("inserisci il numero del voto: ")
    voto13= input("inserisci il numero del voto: ")
    voto14= input("inserisci il numero del voto: ")
    voto15= input("inserisci il numero del voto: ")
    calcolo1= (int(voto1) + int(voto2) + int(voto3) + int(voto4) + int(voto5) + int(voto6) + int(voto7) + int(voto8) + int(voto9) + int(voto10) + int(voto11) + int(voto12) + int(voto13) + int(voto14) + int(voto15))
    calcolo2= (int(calcolo1) / int(totalevoti))
    print(calcolo2)
    input("Da Dario:")
if totalevoti == "16":
    voto1= input("inserisci il numero del voto: ")
    voto2= input("inserisci il numero del voto: ")
    voto3= input("inserisci il numero del voto: ")
    voto4= input("inserisci il numero del voto: ")
    voto5= input("inserisci il numero del voto: ")
    voto6= input("inserisci il numero del voto: ")
    voto7= input("inserisci il numero del voto: ")
    voto8= input("inserisci il numero del voto: ")
    voto9= input("inserisci il numero del voto: ")
    voto10= input("inserisci il numero del voto: ")
    voto11= input("inserisci il numero del voto: ")
    voto12= input("inserisci il numero del voto: ")
    voto13= input("inserisci il numero del voto: ")
    voto14= input("inserisci il numero del voto: ")
    voto15= input("inserisci il numero del voto: ")
    voto16= input("inserisci il numero del voto: ")
    calcolo1= (int(voto1) + int(voto2) + int(voto3) + int(voto4) + int(voto5) + int(voto6) + int(voto7) + int(voto8) + int(voto9) + int(voto10) + int(voto11) + int(voto12) + int(voto13) + int(voto14) + int(voto15) + int(voto16))
    calcolo2= (int(calcolo1) / int(totalevoti))
    print(calcolo2)
    input("Da Dario:")
if totalevoti == "17":
    voto1= input("inserisci il numero del voto: ")
    voto2= input("inserisci il numero del voto: ")
    voto3= input("inserisci il numero del voto: ")
    voto4= input("inserisci il numero del voto: ")
    voto5= input("inserisci il numero del voto: ")
    voto6= input("inserisci il numero del voto: ")
    voto7= input("inserisci il numero del voto: ")
    voto8= input("inserisci il numero del voto: ")
    voto9= input("inserisci il numero del voto: ")
    voto10= input("inserisci il numero del voto: ")
    voto11= input("inserisci il numero del voto: ")
    voto12= input("inserisci il numero del voto: ")
    voto13= input("inserisci il numero del voto: ")
    voto14= input("inserisci il numero del voto: ")
    voto15= input("inserisci il numero del voto: ")
    voto16= input("inserisci il numero del voto: ")
    voto17= input("inserisci il numero del voto: ")
    calcolo1= (int(voto1) + int(voto2) + int(voto3) + int(voto4) + int(voto5) + int(voto6) + int(voto7) + int(voto8) + int(voto9) + int(voto10) + int(voto11) + int(voto12) + int(voto13) + int(voto14) + int(voto15) + int(voto16) + int(voto17))
    calcolo2= (int(calcolo1) / int(totalevoti))
    print(calcolo2)
    input("Da Dario:")
if totalevoti == "18":
    voto1= input("inserisci il numero del voto: ")
    voto2= input("inserisci il numero del voto: ")
    voto3= input("inserisci il numero del voto: ")
    voto4= input("inserisci il numero del voto: ")
    voto5= input("inserisci il numero del voto: ")
    voto6= input("inserisci il numero del voto: ")
    voto7= input("inserisci il numero del voto: ")
    voto8= input("inserisci il numero del voto: ")
    voto9= input("inserisci il numero del voto: ")
    voto10= input("inserisci il numero del voto: ")
    voto11= input("inserisci il numero del voto: ")
    voto12= input("inserisci il numero del voto: ")
    voto13= input("inserisci il numero del voto: ")
    voto14= input("inserisci il numero del voto: ")
    voto15= input("inserisci il numero del voto: ")
    voto16= input("inserisci il numero del voto: ")
    voto17= input("inserisci il numero del voto: ")
    voto18= input("inserisci il numero del voto: ")
    calcolo1= (int(voto1) + int(voto2) + int(voto3) + int(voto4) + int(voto5) + int(voto6) + int(voto7) + int(voto8) + int(voto9) + int(voto10) + int(voto11) + int(voto12) + int(voto13) + int(voto14) + int(voto15) + int(voto16) + int(voto17) + int(voto18))
    calcolo2= (int(calcolo1) / int(totalevoti))
    print(calcolo2)
    input("Da Dario:")
if totalevoti == "19":
    voto1= input("inserisci il numero del voto: ")
    voto2= input("inserisci il numero del voto: ")
    voto3= input("inserisci il numero del voto: ")
    voto4= input("inserisci il numero del voto: ")
    voto5= input("inserisci il numero del voto: ")
    voto6= input("inserisci il numero del voto: ")
    voto7= input("inserisci il numero del voto: ")
    voto8= input("inserisci il numero del voto: ")
    voto9= input("inserisci il numero del voto: ")
    voto10= input("inserisci il numero del voto: ")
    voto11= input("inserisci il numero del voto: ")
    voto12= input("inserisci il numero del voto: ")
    voto13= input("inserisci il numero del voto: ")
    voto14= input("inserisci il numero del voto: ")
    voto15= input("inserisci il numero del voto: ")
    voto16= input("inserisci il numero del voto: ")
    voto17= input("inserisci il numero del voto: ")
    voto18= input("inserisci il numero del voto: ")
    voto19= input("inserisci il numero del voto: ")
    calcolo1= (int(voto1) + int(voto2) + int(voto3) + int(voto4) + int(voto5) + int(voto6) + int(voto7) + int(voto8) + int(voto9) + int(voto10) + int(voto11) + int(voto12) + int(voto13) + int(voto14) + int(voto15) + int(voto16) + int(voto17) + int(voto18) + int(voto19))
    calcolo2= (int(calcolo1) / int(totalevoti))
    print(calcolo2)
    input("Da Dario:")
if totalevoti == "20":
    voto1= input("inserisci il numero del voto: ")
    voto2= input("inserisci il numero del voto: ")
    voto3= input("inserisci il numero del voto: ")
    voto4= input("inserisci il numero del voto: ")
    voto5= input("inserisci il numero del voto: ")
    voto6= input("inserisci il numero del voto: ")
    voto7= input("inserisci il numero del voto: ")
    voto8= input("inserisci il numero del voto: ")
    voto9= input("inserisci il numero del voto: ")
    voto10= input("inserisci il numero del voto: ")
    voto11= input("inserisci il numero del voto: ")
    voto12= input("inserisci il numero del voto: ")
    voto13= input("inserisci il numero del voto: ")
    voto14= input("inserisci il numero del voto: ")
    voto15= input("inserisci il numero del voto: ")
    voto16= input("inserisci il numero del voto: ")
    voto17= input("inserisci il numero del voto: ")
    voto18= input("inserisci il numero del voto: ")
    voto19= input("inserisci il numero del voto: ")
    voto20= input("inserisci il numero del voto: ")
    calcolo1= (int(voto1) + int(voto2) + int(voto3) + int(voto4) + int(voto5) + int(voto6) + int(voto7) + int(voto8) + int(voto9) + int(voto10) + int(voto11) + int(voto12) + int(voto13) + int(voto14) + int(voto15) + int(voto16) + int(voto17) + int(voto18) + int(voto19) + int(voto20))
    calcolo2= (int(calcolo1) / int(totalevoti))
    print(calcolo2)
    input("Da Dario:")
if totalevoti == "21":
    voto1= input("inserisci il numero del voto: ")
    voto2= input("inserisci il numero del voto: ")
    voto3= input("inserisci il numero del voto: ")
    voto4= input("inserisci il numero del voto: ")
    voto5= input("inserisci il numero del voto: ")
    voto6= input("inserisci il numero del voto: ")
    voto7= input("inserisci il numero del voto: ")
    voto8= input("inserisci il numero del voto: ")
    voto9= input("inserisci il numero del voto: ")
    voto10= input("inserisci il numero del voto: ")
    voto11= input("inserisci il numero del voto: ")
    voto12= input("inserisci il numero del voto: ")
    voto13= input("inserisci il numero del voto: ")
    voto14= input("inserisci il numero del voto: ")
    voto15= input("inserisci il numero del voto: ")
    voto16= input("inserisci il numero del voto: ")
    voto17= input("inserisci il numero del voto: ")
    voto18= input("inserisci il numero del voto: ")
    voto19= input("inserisci il numero del voto: ")
    voto20= input("inserisci il numero del voto: ")
    voto21= input("inserisci il numero del voto: ")
    calcolo1= (int(voto1) + int(voto2) + int(voto3) + int(voto4) + int(voto5) + int(voto6) + int(voto7) + int(voto8) + int(voto9) + int(voto10) + int(voto11) + int(voto12) + int(voto13) + int(voto14) + int(voto15) + int(voto16) + int(voto17) + int(voto18) + int(voto19) + int(voto20) + int(voto21))
    calcolo2= (int(calcolo1) / int(totalevoti))
    print(calcolo2)
    input("Da Dario:")
if totalevoti == "22":
    voto1= input("inserisci il numero del voto: ")
    voto2= input("inserisci il numero del voto: ")
    voto3= input("inserisci il numero del voto: ")
    voto4= input("inserisci il numero del voto: ")
    voto5= input("inserisci il numero del voto: ")
    voto6= input("inserisci il numero del voto: ")
    voto7= input("inserisci il numero del voto: ")
    voto8= input("inserisci il numero del voto: ")
    voto9= input("inserisci il numero del voto: ")
    voto10= input("inserisci il numero del voto: ")
    voto11= input("inserisci il numero del voto: ")
    voto12= input("inserisci il numero del voto: ")
    voto13= input("inserisci il numero del voto: ")
    voto14= input("inserisci il numero del voto: ")
    voto15= input("inserisci il numero del voto: ")
    voto16= input("inserisci il numero del voto: ")
    voto17= input("inserisci il numero del voto: ")
    voto18= input("inserisci il numero del voto: ")
    voto19= input("inserisci il numero del voto: ")
    voto20= input("inserisci il numero del voto: ")
    voto21= input("inserisci il numero del voto: ")
    voto22= input("inserisci il numero del voto: ")
    calcolo1= (int(voto1) + int(voto2) + int(voto3) + int(voto4) + int(voto5) + int(voto6) + int(voto7) + int(voto8) + int(voto9) + int(voto10) + int(voto11) + int(voto12) + int(voto13) + int(voto14) + int(voto15) + int(voto16) + int(voto17) + int(voto18) + int(voto19) + int(voto20) + int(voto21) + int(voto22) + int(voto23))
    calcolo2= (int(calcolo1) / int(totalevoti))
    print(calcolo2)
    input("Da Dario:")
if totalevoti == "23":
    voto1= input("inserisci il numero del voto: ")
    voto2= input("inserisci il numero del voto: ")
    voto3= input("inserisci il numero del voto: ")
    voto4= input("inserisci il numero del voto: ")
    voto5= input("inserisci il numero del voto: ")
    voto6= input("inserisci il numero del voto: ")
    voto7= input("inserisci il numero del voto: ")
    voto8= input("inserisci il numero del voto: ")
    voto9= input("inserisci il numero del voto: ")
    voto10= input("inserisci il numero del voto: ")
    voto11= input("inserisci il numero del voto: ")
    voto12= input("inserisci il numero del voto: ")
    voto13= input("inserisci il numero del voto: ")
    voto14= input("inserisci il numero del voto: ")
    voto15= input("inserisci il numero del voto: ")
    voto16= input("inserisci il numero del voto: ")
    voto17= input("inserisci il numero del voto: ")
    voto18= input("inserisci il numero del voto: ")
    voto19= input("inserisci il numero del voto: ")
    voto20= input("inserisci il numero del voto: ")
    voto21= input("inserisci il numero del voto: ")
    voto22= input("inserisci il numero del voto: ")
    voto23= input("inserisci il numero del voto: ")
    calcolo1= (int(voto1) + int(voto2) + int(voto3) + int(voto4) + int(voto5) + int(voto6) + int(voto7) + int(voto8) + int(voto9) + int(voto10) + int(voto11) + int(voto12) + int(voto13) + int(voto14) + int(voto15) + int(voto16) + int(voto17) + int(voto18) + int(voto19) + int(voto20) + int(voto21) + int(voto22) + int(voto23))
    calcolo2= (int(calcolo1) / int(totalevoti))
    print(calcolo2)
    input("Da Dario:")
if totalevoti == "24":
    voto1= input("inserisci il numero del voto: ")
    voto2= input("inserisci il numero del voto: ")
    voto3= input("inserisci il numero del voto: ")
    voto4= input("inserisci il numero del voto: ")
    voto5= input("inserisci il numero del voto: ")
    voto6= input("inserisci il numero del voto: ")
    voto7= input("inserisci il numero del voto: ")
    voto8= input("inserisci il numero del voto: ")
    voto9= input("inserisci il numero del voto: ")
    voto10= input("inserisci il numero del voto: ")
    voto11= input("inserisci il numero del voto: ")
    voto12= input("inserisci il numero del voto: ")
    voto13= input("inserisci il numero del voto: ")
    voto14= input("inserisci il numero del voto: ")
    voto15= input("inserisci il numero del voto: ")
    voto16= input("inserisci il numero del voto: ")
    voto17= input("inserisci il numero del voto: ")
    voto18= input("inserisci il numero del voto: ")
    voto19= input("inserisci il numero del voto: ")
    voto20= input("inserisci il numero del voto: ")
    voto21= input("inserisci il numero del voto: ")
    voto22= input("inserisci il numero del voto: ")
    voto23= input("inserisci il numero del voto: ")
    voto24= input("inserisci il numero del voto: ")
    calcolo1= (int(voto1) + int(voto2) + int(voto3) + int(voto4) + int(voto5) + int(voto6) + int(voto7) + int(voto8) + int(voto9) + int(voto10) + int(voto11) + int(voto12) + int(voto13) + int(voto14) + int(voto15) + int(voto16) + int(voto17) + int(voto18) + int(voto19) + int(voto20) + int(voto21) + int(voto22) + int(voto23) + int(voto24))
    calcolo2= (int(calcolo1) / int(totalevoti))
    print(calcolo2)
    input("Da Dario:")
if totalevoti == "25":
    voto1= input("inserisci il numero del voto: ")
    voto2= input("inserisci il numero del voto: ")
    voto3= input("inserisci il numero del voto: ")
    voto4= input("inserisci il numero del voto: ")
    voto5= input("inserisci il numero del voto: ")
    voto6= input("inserisci il numero del voto: ")
    voto7= input("inserisci il numero del voto: ")
    voto8= input("inserisci il numero del voto: ")
    voto9= input("inserisci il numero del voto: ")
    voto10= input("inserisci il numero del voto: ")
    voto11= input("inserisci il numero del voto: ")
    voto12= input("inserisci il numero del voto: ")
    voto13= input("inserisci il numero del voto: ")
    voto14= input("inserisci il numero del voto: ")
    voto15= input("inserisci il numero del voto: ")
    voto16= input("inserisci il numero del voto: ")
    voto17= input("inserisci il numero del voto: ")
    voto18= input("inserisci il numero del voto: ")
    voto19= input("inserisci il numero del voto: ")
    voto20= input("inserisci il numero del voto: ")
    voto21= input("inserisci il numero del voto: ")
    voto22= input("inserisci il numero del voto: ")
    voto23= input("inserisci il numero del voto: ")
    voto24= input("inserisci il numero del voto: ")
    voto25= input("inserisci il numero del voto: ")
    calcolo1= (int(voto1) + int(voto2) + int(voto3) + int(voto4) + int(voto5) + int(voto6) + int(voto7) + int(voto8) + int(voto9) + int(voto10) + int(voto11) + int(voto12) + int(voto13) + int(voto14) + int(voto15) + int(voto16) + int(voto17) + int(voto18) + int(voto19) + int(voto20) + int(voto21) + int(voto22) + int(voto23) + int(voto24) + int(voto25))
    calcolo2= (int(calcolo1) / int(totalevoti))
    print(calcolo2)
    input("Da Dario:")
if totalevoti == "26":
    voto1= input("inserisci il numero del voto: ")
    voto2= input("inserisci il numero del voto: ")
    voto3= input("inserisci il numero del voto: ")
    voto4= input("inserisci il numero del voto: ")
    voto5= input("inserisci il numero del voto: ")
    voto6= input("inserisci il numero del voto: ")
    voto7= input("inserisci il numero del voto: ")
    voto8= input("inserisci il numero del voto: ")
    voto9= input("inserisci il numero del voto: ")
    voto10= input("inserisci il numero del voto: ")
    voto11= input("inserisci il numero del voto: ")
    voto12= input("inserisci il numero del voto: ")
    voto13= input("inserisci il numero del voto: ")
    voto14= input("inserisci il numero del voto: ")
    voto15= input("inserisci il numero del voto: ")
    voto16= input("inserisci il numero del voto: ")
    voto17= input("inserisci il numero del voto: ")
    voto18= input("inserisci il numero del voto: ")
    voto19= input("inserisci il numero del voto: ")
    voto20= input("inserisci il numero del voto: ")
    voto21= input("inserisci il numero del voto: ")
    voto22= input("inserisci il numero del voto: ")
    voto23= input("inserisci il numero del voto: ")
    voto24= input("inserisci il numero del voto: ")
    voto25= input("inserisci il numero del voto: ")
    voto26= input("inserisci il numero del voto: ")
    calcolo1= (int(voto1) + int(voto2) + int(voto3) + int(voto4) + int(voto5) + int(voto6) + int(voto7) + int(voto8) + int(voto9) + int(voto10) + int(voto11) + int(voto12) + int(voto13) + int(voto14) + int(voto15) + int(voto16) + int(voto17) + int(voto18) + int(voto19) + int(voto20) + int(voto21) + int(voto22) + int(voto23) + int(voto24) + int(voto25) + int(voto26))
    calcolo2= (int(calcolo1) / int(totalevoti))
    print(calcolo2)
    input("Da Dario:")
if totalevoti == "27":
    voto1= input("inserisci il numero del voto: ")
    voto2= input("inserisci il numero del voto: ")
    voto3= input("inserisci il numero del voto: ")
    voto4= input("inserisci il numero del voto: ")
    voto5= input("inserisci il numero del voto: ")
    voto6= input("inserisci il numero del voto: ")
    voto7= input("inserisci il numero del voto: ")
    voto8= input("inserisci il numero del voto: ")
    voto9= input("inserisci il numero del voto: ")
    voto10= input("inserisci il numero del voto: ")
    voto11= input("inserisci il numero del voto: ")
    voto12= input("inserisci il numero del voto: ")
    voto13= input("inserisci il numero del voto: ")
    voto14= input("inserisci il numero del voto: ")
    voto15= input("inserisci il numero del voto: ")
    voto16= input("inserisci il numero del voto: ")
    voto17= input("inserisci il numero del voto: ")
    voto18= input("inserisci il numero del voto: ")
    voto19= input("inserisci il numero del voto: ")
    voto20= input("inserisci il numero del voto: ")
    voto21= input("inserisci il numero del voto: ")
    voto22= input("inserisci il numero del voto: ")
    voto23= input("inserisci il numero del voto: ")
    voto24= input("inserisci il numero del voto: ")
    voto25= input("inserisci il numero del voto: ")
    voto26= input("inserisci il numero del voto: ")
    voto27= input("inserisci il numero del voto: ")
    calcolo1= (int(voto1) + int(voto2) + int(voto3) + int(voto4) + int(voto5) + int(voto6) + int(voto7) + int(voto8) + int(voto9) + int(voto10) + int(voto11) + int(voto12) + int(voto13) + int(voto14) + int(voto15) + int(voto16) + int(voto17) + int(voto18) + int(voto19) + int(voto20) + int(voto21) + int(voto22) + int(voto23) + int(voto24) + int(voto25) + int(voto26) + int(voto27))
    calcolo2= (int(calcolo1) / int(totalevoti))
    print(calcolo2)
    input("Da Dario:")
if totalevoti == "28":
    voto1= input("inserisci il numero del voto: ")
    voto2= input("inserisci il numero del voto: ")
    voto3= input("inserisci il numero del voto: ")
    voto4= input("inserisci il numero del voto: ")
    voto5= input("inserisci il numero del voto: ")
    voto6= input("inserisci il numero del voto: ")
    voto7= input("inserisci il numero del voto: ")
    voto8= input("inserisci il numero del voto: ")
    voto9= input("inserisci il numero del voto: ")
    voto10= input("inserisci il numero del voto: ")
    voto11= input("inserisci il numero del voto: ")
    voto12= input("inserisci il numero del voto: ")
    voto13= input("inserisci il numero del voto: ")
    voto14= input("inserisci il numero del voto: ")
    voto15= input("inserisci il numero del voto: ")
    voto16= input("inserisci il numero del voto: ")
    voto17= input("inserisci il numero del voto: ")
    voto18= input("inserisci il numero del voto: ")
    voto19= input("inserisci il numero del voto: ")
    voto20= input("inserisci il numero del voto: ")
    voto21= input("inserisci il numero del voto: ")
    voto22= input("inserisci il numero del voto: ")
    voto23= input("inserisci il numero del voto: ")
    voto24= input("inserisci il numero del voto: ")
    voto25= input("inserisci il numero del voto: ")
    voto26= input("inserisci il numero del voto: ")
    voto27= input("inserisci il numero del voto: ")
    voto28= input("inserisci il numero del voto: ")
    calcolo1= (int(voto1) + int(voto2) + int(voto3) + int(voto4) + int(voto5) + int(voto6) + int(voto7) + int(voto8) + int(voto9) + int(voto10) + int(voto11) + int(voto12) + int(voto13) + int(voto14) + int(voto15) + int(voto16) + int(voto17) + int(voto18) + int(voto19) + int(voto20) + int(voto21) + int(voto22) + int(voto23) + int(voto24) + int(voto25) + int(voto26) + int(voto27) + int(voto28))
    calcolo2= (int(calcolo1) / int(totalevoti))
    print(calcolo2)
    input("Da Dario:")
if totalevoti == "29":
    voto1= input("inserisci il numero del voto: ")
    voto2= input("inserisci il numero del voto: ")
    voto3= input("inserisci il numero del voto: ")
    voto4= input("inserisci il numero del voto: ")
    voto5= input("inserisci il numero del voto: ")
    voto6= input("inserisci il numero del voto: ")
    voto7= input("inserisci il numero del voto: ")
    voto8= input("inserisci il numero del voto: ")
    voto9= input("inserisci il numero del voto: ")
    voto10= input("inserisci il numero del voto: ")
    voto11= input("inserisci il numero del voto: ")
    voto12= input("inserisci il numero del voto: ")
    voto13= input("inserisci il numero del voto: ")
    voto14= input("inserisci il numero del voto: ")
    voto15= input("inserisci il numero del voto: ")
    voto16= input("inserisci il numero del voto: ")
    voto17= input("inserisci il numero del voto: ")
    voto18= input("inserisci il numero del voto: ")
    voto19= input("inserisci il numero del voto: ")
    voto20= input("inserisci il numero del voto: ")
    voto21= input("inserisci il numero del voto: ")
    voto22= input("inserisci il numero del voto: ")
    voto23= input("inserisci il numero del voto: ")
    voto24= input("inserisci il numero del voto: ")
    voto25= input("inserisci il numero del voto: ")
    voto26= input("inserisci il numero del voto: ")
    voto27= input("inserisci il numero del voto: ")
    voto28= input("inserisci il numero del voto: ")
    voto29= input("inserisci il numero del voto: ")
    calcolo1= (int(voto1) + int(voto2) + int(voto3) + int(voto4) + int(voto5) + int(voto6) + int(voto7) + int(voto8) + int(voto9) + int(voto10) + int(voto11) + int(voto12) + int(voto13) + int(voto14) + int(voto15) + int(voto16) + int(voto17) + int(voto18) + int(voto19) + int(voto20) + int(voto21) + int(voto22) + int(voto23) + int(voto24) + int(voto25) + int(voto26) + int(voto27) + int(voto28) + int(voto29))
    calcolo2= (int(calcolo1) / int(totalevoti))
    print(calcolo2)
    input("Da Dario:")
if totalevoti == "30":
    voto1= input("inserisci il numero del voto: ")
    voto2= input("inserisci il numero del voto: ")
    voto3= input("inserisci il numero del voto: ")
    voto4= input("inserisci il numero del voto: ")
    voto5= input("inserisci il numero del voto: ")
    voto6= input("inserisci il numero del voto: ")
    voto7= input("inserisci il numero del voto: ")
    voto8= input("inserisci il numero del voto: ")
    voto9= input("inserisci il numero del voto: ")
    voto10= input("inserisci il numero del voto: ")
    voto11= input("inserisci il numero del voto: ")
    voto12= input("inserisci il numero del voto: ")
    voto13= input("inserisci il numero del voto: ")
    voto14= input("inserisci il numero del voto: ")
    voto15= input("inserisci il numero del voto: ")
    voto16= input("inserisci il numero del voto: ")
    voto17= input("inserisci il numero del voto: ")
    voto18= input("inserisci il numero del voto: ")
    voto19= input("inserisci il numero del voto: ")
    voto20= input("inserisci il numero del voto: ")
    voto21= input("inserisci il numero del voto: ")
    voto22= input("inserisci il numero del voto: ")
    voto23= input("inserisci il numero del voto: ")
    voto24= input("inserisci il numero del voto: ")
    voto25= input("inserisci il numero del voto: ")
    voto26= input("inserisci il numero del voto: ")
    voto27= input("inserisci il numero del voto: ")
    voto28= input("inserisci il numero del voto: ")
    voto29= input("inserisci il numero del voto: ")
    voto30= input("inserisci il numero del voto: ")
    calcolo1= (int(voto1) + int(voto2) + int(voto3) + int(voto4) + int(voto5) + int(voto6) + int(voto7) + int(voto8) + int(voto9) + int(voto10) + int(voto11) + int(voto12) + int(voto13) + int(voto14) + int(voto15) + int(voto16) + int(voto17) + int(voto18) + int(voto19) + int(voto20) + int(voto21) + int(voto22) + int(voto23) + int(voto24) + int(voto25) + int(voto26) + int(voto27) + int(voto28) + int(voto29) + int(voto30))
    calcolo2= (int(calcolo1) / int(totalevoti))
    print(calcolo2)
    input("Da Dario:")
if totalevoti == "31":
    voto1= input("inserisci il numero del voto: ")
    voto2= input("inserisci il numero del voto: ")
    voto3= input("inserisci il numero del voto: ")
    voto4= input("inserisci il numero del voto: ")
    voto5= input("inserisci il numero del voto: ")
    voto6= input("inserisci il numero del voto: ")
    voto7= input("inserisci il numero del voto: ")
    voto8= input("inserisci il numero del voto: ")
    voto9= input("inserisci il numero del voto: ")
    voto10= input("inserisci il numero del voto: ")
    voto11= input("inserisci il numero del voto: ")
    voto12= input("inserisci il numero del voto: ")
    voto13= input("inserisci il numero del voto: ")
    voto14= input("inserisci il numero del voto: ")
    voto15= input("inserisci il numero del voto: ")
    voto16= input("inserisci il numero del voto: ")
    voto17= input("inserisci il numero del voto: ")
    voto18= input("inserisci il numero del voto: ")
    voto19= input("inserisci il numero del voto: ")
    voto20= input("inserisci il numero del voto: ")
    voto21= input("inserisci il numero del voto: ")
    voto22= input("inserisci il numero del voto: ")
    voto23= input("inserisci il numero del voto: ")
    voto24= input("inserisci il numero del voto: ")
    voto25= input("inserisci il numero del voto: ")
    voto26= input("inserisci il numero del voto: ")
    voto27= input("inserisci il numero del voto: ")
    voto28= input("inserisci il numero del voto: ")
    voto29= input("inserisci il numero del voto: ")
    voto30= input("inserisci il numero del voto: ")
    voto31= input("inserisci il numero del voto: ")
    calcolo1= (int(voto1) + int(voto2) + int(voto3) + int(voto4) + int(voto5) + int(voto6) + int(voto7) + int(voto8) + int(voto9) + int(voto10) + int(voto11) + int(voto12) + int(voto13) + int(voto14) + int(voto15) + int(voto16) + int(voto17) + int(voto18) + int(voto19) + int(voto20) + int(voto21) + int(voto22) + int(voto23) + int(voto24) + int(voto25) + int(voto26) + int(voto27) + int(voto28) + int(voto29) + int(voto30) + int(voto31))
    calcolo2= (int(calcolo1) / int(totalevoti))
    print(calcolo2)
    input("Da Dario:")
if totalevoti == "32":
    voto1= input("inserisci il numero del voto: ")
    voto2= input("inserisci il numero del voto: ")
    voto3= input("inserisci il numero del voto: ")
    voto4= input("inserisci il numero del voto: ")
    voto5= input("inserisci il numero del voto: ")
    voto6= input("inserisci il numero del voto: ")
    voto7= input("inserisci il numero del voto: ")
    voto8= input("inserisci il numero del voto: ")
    voto9= input("inserisci il numero del voto: ")
    voto10= input("inserisci il numero del voto: ")
    voto11= input("inserisci il numero del voto: ")
    voto12= input("inserisci il numero del voto: ")
    voto13= input("inserisci il numero del voto: ")
    voto14= input("inserisci il numero del voto: ")
    voto15= input("inserisci il numero del voto: ")
    voto16= input("inserisci il numero del voto: ")
    voto17= input("inserisci il numero del voto: ")
    voto18= input("inserisci il numero del voto: ")
    voto19= input("inserisci il numero del voto: ")
    voto20= input("inserisci il numero del voto: ")
    voto21= input("inserisci il numero del voto: ")
    voto22= input("inserisci il numero del voto: ")
    voto23= input("inserisci il numero del voto: ")
    voto24= input("inserisci il numero del voto: ")
    voto25= input("inserisci il numero del voto: ")
    voto26= input("inserisci il numero del voto: ")
    voto27= input("inserisci il numero del voto: ")
    voto28= input("inserisci il numero del voto: ")
    voto29= input("inserisci il numero del voto: ")
    voto30= input("inserisci il numero del voto: ")
    voto31= input("inserisci il numero del voto: ")
    voto32= input("inserisci il numero del voto: ")
    calcolo1= (int(voto1) + int(voto2) + int(voto3) + int(voto4) + int(voto5) + int(voto6) + int(voto7) + int(voto8) + int(voto9) + int(voto10) + int(voto11) + int(voto12) + int(voto13) + int(voto14) + int(voto15) + int(voto16) + int(voto17) + int(voto18) + int(voto19) + int(voto20) + int(voto21) + int(voto22) + int(voto23) + int(voto24) + int(voto25) + int(voto26) + int(voto27) + int(voto28) + int(voto29) + int(voto30) + int(voto31) + int(voto32))
    calcolo2= (int(calcolo1) / int(totalevoti))
    print(calcolo2)
    input("Da Dario:")
if totalevoti == "33":
    voto1= input("inserisci il numero del voto: ")
    voto2= input("inserisci il numero del voto: ")
    voto3= input("inserisci il numero del voto: ")
    voto4= input("inserisci il numero del voto: ")
    voto5= input("inserisci il numero del voto: ")
    voto6= input("inserisci il numero del voto: ")
    voto7= input("inserisci il numero del voto: ")
    voto8= input("inserisci il numero del voto: ")
    voto9= input("inserisci il numero del voto: ")
    voto10= input("inserisci il numero del voto: ")
    voto11= input("inserisci il numero del voto: ")
    voto12= input("inserisci il numero del voto: ")
    voto13= input("inserisci il numero del voto: ")
    voto14= input("inserisci il numero del voto: ")
    voto15= input("inserisci il numero del voto: ")
    voto16= input("inserisci il numero del voto: ")
    voto17= input("inserisci il numero del voto: ")
    voto18= input("inserisci il numero del voto: ")
    voto19= input("inserisci il numero del voto: ")
    voto20= input("inserisci il numero del voto: ")
    voto21= input("inserisci il numero del voto: ")
    voto22= input("inserisci il numero del voto: ")
    voto23= input("inserisci il numero del voto: ")
    voto24= input("inserisci il numero del voto: ")
    voto25= input("inserisci il numero del voto: ")
    voto26= input("inserisci il numero del voto: ")
    voto27= input("inserisci il numero del voto: ")
    voto28= input("inserisci il numero del voto: ")
    voto29= input("inserisci il numero del voto: ")
    voto30= input("inserisci il numero del voto: ")
    voto31= input("inserisci il numero del voto: ")
    voto32= input("inserisci il numero del voto: ")
    voto33= input("inserisci il numero del voto: ")
    calcolo1= (int(voto1) + int(voto2) + int(voto3) + int(voto4) + int(voto5) + int(voto6) + int(voto7) + int(voto8) + int(voto9) + int(voto10) + int(voto11) + int(voto12) + int(voto13) + int(voto14) + int(voto15) + int(voto16) + int(voto17) + int(voto18) + int(voto19) + int(voto20) + int(voto21) + int(voto22) + int(voto23) + int(voto24) + int(voto25) + int(voto26) + int(voto27) + int(voto28) + int(voto29) + int(voto30) + int(voto31) + int(voto32) + int(voto33))
    calcolo2= (int(calcolo1) / int(totalevoti))
    print(calcolo2)
    input("Da Dario:")
if totalevoti == "34":
    voto1= input("inserisci il numero del voto: ")
    voto2= input("inserisci il numero del voto: ")
    voto3= input("inserisci il numero del voto: ")
    voto4= input("inserisci il numero del voto: ")
    voto5= input("inserisci il numero del voto: ")
    voto6= input("inserisci il numero del voto: ")
    voto7= input("inserisci il numero del voto: ")
    voto8= input("inserisci il numero del voto: ")
    voto9= input("inserisci il numero del voto: ")
    voto10= input("inserisci il numero del voto: ")
    voto11= input("inserisci il numero del voto: ")
    voto12= input("inserisci il numero del voto: ")
    voto13= input("inserisci il numero del voto: ")
    voto14= input("inserisci il numero del voto: ")
    voto15= input("inserisci il numero del voto: ")
    voto16= input("inserisci il numero del voto: ")
    voto17= input("inserisci il numero del voto: ")
    voto18= input("inserisci il numero del voto: ")
    voto19= input("inserisci il numero del voto: ")
    voto20= input("inserisci il numero del voto: ")
    voto21= input("inserisci il numero del voto: ")
    voto22= input("inserisci il numero del voto: ")
    voto23= input("inserisci il numero del voto: ")
    voto24= input("inserisci il numero del voto: ")
    voto25= input("inserisci il numero del voto: ")
    voto26= input("inserisci il numero del voto: ")
    voto27= input("inserisci il numero del voto: ")
    voto28= input("inserisci il numero del voto: ")
    voto29= input("inserisci il numero del voto: ")
    voto30= input("inserisci il numero del voto: ")
    voto31= input("inserisci il numero del voto: ")
    voto32= input("inserisci il numero del voto: ")
    voto33= input("inserisci il numero del voto: ")
    voto34= input("inserisci il numero del voto: ")
    calcolo1= (int(voto1) + int(voto2) + int(voto3) + int(voto4) + int(voto5) + int(voto6) + int(voto7) + int(voto8) + int(voto9) + int(voto10) + int(voto11) + int(voto12) + int(voto13) + int(voto14) + int(voto15) + int(voto16) + int(voto17) + int(voto18) + int(voto19) + int(voto20) + int(voto21) + int(voto22) + int(voto23) + int(voto24) + int(voto25) + int(voto26) + int(voto27) + int(voto28) + int(voto29) + int(voto30) + int(voto31) + int(voto32) + int(voto33) + int(voto34))
    calcolo2= (int(calcolo1) / int(totalevoti))
    print(calcolo2)
    input("Da Dario:")
if totalevoti == "35":
    voto1= input("inserisci il numero del voto: ")
    voto2= input("inserisci il numero del voto: ")
    voto3= input("inserisci il numero del voto: ")
    voto4= input("inserisci il numero del voto: ")
    voto5= input("inserisci il numero del voto: ")
    voto6= input("inserisci il numero del voto: ")
    voto7= input("inserisci il numero del voto: ")
    voto8= input("inserisci il numero del voto: ")
    voto9= input("inserisci il numero del voto: ")
    voto10= input("inserisci il numero del voto: ")
    voto11= input("inserisci il numero del voto: ")
    voto12= input("inserisci il numero del voto: ")
    voto13= input("inserisci il numero del voto: ")
    voto14= input("inserisci il numero del voto: ")
    voto15= input("inserisci il numero del voto: ")
    voto16= input("inserisci il numero del voto: ")
    voto17= input("inserisci il numero del voto: ")
    voto18= input("inserisci il numero del voto: ")
    voto19= input("inserisci il numero del voto: ")
    voto20= input("inserisci il numero del voto: ")
    voto21= input("inserisci il numero del voto: ")
    voto22= input("inserisci il numero del voto: ")
    voto23= input("inserisci il numero del voto: ")
    voto24= input("inserisci il numero del voto: ")
    voto25= input("inserisci il numero del voto: ")
    voto26= input("inserisci il numero del voto: ")
    voto27= input("inserisci il numero del voto: ")
    voto28= input("inserisci il numero del voto: ")
    voto29= input("inserisci il numero del voto: ")
    voto30= input("inserisci il numero del voto: ")
    voto31= input("inserisci il numero del voto: ")
    voto32= input("inserisci il numero del voto: ")
    voto33= input("inserisci il numero del voto: ")
    voto34= input("inserisci il numero del voto: ")
    voto35= input("inserisci il numero del voto: ")
    calcolo1= (int(voto1) + int(voto2) + int(voto3) + int(voto4) + int(voto5) + int(voto6) + int(voto7) + int(voto8) + int(voto9) + int(voto10) + int(voto11) + int(voto12) + int(voto13) + int(voto14) + int(voto15) + int(voto16) + int(voto17) + int(voto18) + int(voto19) + int(voto20) + int(voto21) + int(voto22) + int(voto23) + int(voto24) + int(voto25) + int(voto26) + int(voto27) + int(voto28) + int(voto29) + int(voto30) + int(voto31) + int(voto32) + int(voto33) + int(voto34) + int(voto35))
    calcolo2= (int(calcolo1) / int(totalevoti))
    print(calcolo2)
    input("Da Dario:")
if totalevoti == "36":
    voto1= input("inserisci il numero del voto: ")
    voto2= input("inserisci il numero del voto: ")
    voto3= input("inserisci il numero del voto: ")
    voto4= input("inserisci il numero del voto: ")
    voto5= input("inserisci il numero del voto: ")
    voto6= input("inserisci il numero del voto: ")
    voto7= input("inserisci il numero del voto: ")
    voto8= input("inserisci il numero del voto: ")
    voto9= input("inserisci il numero del voto: ")
    voto10= input("inserisci il numero del voto: ")
    voto11= input("inserisci il numero del voto: ")
    voto12= input("inserisci il numero del voto: ")
    voto13= input("inserisci il numero del voto: ")
    voto14= input("inserisci il numero del voto: ")
    voto15= input("inserisci il numero del voto: ")
    voto16= input("inserisci il numero del voto: ")
    voto17= input("inserisci il numero del voto: ")
    voto18= input("inserisci il numero del voto: ")
    voto19= input("inserisci il numero del voto: ")
    voto20= input("inserisci il numero del voto: ")
    voto21= input("inserisci il numero del voto: ")
    voto22= input("inserisci il numero del voto: ")
    voto23= input("inserisci il numero del voto: ")
    voto24= input("inserisci il numero del voto: ")
    voto25= input("inserisci il numero del voto: ")
    voto26= input("inserisci il numero del voto: ")
    voto27= input("inserisci il numero del voto: ")
    voto28= input("inserisci il numero del voto: ")
    voto29= input("inserisci il numero del voto: ")
    voto30= input("inserisci il numero del voto: ")
    voto31= input("inserisci il numero del voto: ")
    voto32= input("inserisci il numero del voto: ")
    voto33= input("inserisci il numero del voto: ")
    voto34= input("inserisci il numero del voto: ")
    voto35= input("inserisci il numero del voto: ")
    voto36= input("inserisci il numero del voto: ")
    calcolo1= (int(voto1) + int(voto2) + int(voto3) + int(voto4) + int(voto5) + int(voto6) + int(voto7) + int(voto8) + int(voto9) + int(voto10) + int(voto11) + int(voto12) + int(voto13) + int(voto14) + int(voto15) + int(voto16) + int(voto17) + int(voto18) + int(voto19) + int(voto20) + int(voto21) + int(voto22) + int(voto23) + int(voto24) + int(voto25) + int(voto26) + int(voto27) + int(voto28) + int(voto29) + int(voto30) + int(voto31) + int(voto32) + int(voto33) + int(voto34) + int(voto35) + int(voto36))
    calcolo2= (int(calcolo1) / int(totalevoti))
    print(calcolo2)
    input("Da Dario:")
if totalevoti == "37":
    voto1= input("inserisci il numero del voto: ")
    voto2= input("inserisci il numero del voto: ")
    voto3= input("inserisci il numero del voto: ")
    voto4= input("inserisci il numero del voto: ")
    voto5= input("inserisci il numero del voto: ")
    voto6= input("inserisci il numero del voto: ")
    voto7= input("inserisci il numero del voto: ")
    voto8= input("inserisci il numero del voto: ")
    voto9= input("inserisci il numero del voto: ")
    voto10= input("inserisci il numero del voto: ")
    voto11= input("inserisci il numero del voto: ")
    voto12= input("inserisci il numero del voto: ")
    voto13= input("inserisci il numero del voto: ")
    voto14= input("inserisci il numero del voto: ")
    voto15= input("inserisci il numero del voto: ")
    voto16= input("inserisci il numero del voto: ")
    voto17= input("inserisci il numero del voto: ")
    voto18= input("inserisci il numero del voto: ")
    voto19= input("inserisci il numero del voto: ")
    voto20= input("inserisci il numero del voto: ")
    voto21= input("inserisci il numero del voto: ")
    voto22= input("inserisci il numero del voto: ")
    voto23= input("inserisci il numero del voto: ")
    voto24= input("inserisci il numero del voto: ")
    voto25= input("inserisci il numero del voto: ")
    voto26= input("inserisci il numero del voto: ")
    voto27= input("inserisci il numero del voto: ")
    voto28= input("inserisci il numero del voto: ")
    voto29= input("inserisci il numero del voto: ")
    voto30= input("inserisci il numero del voto: ")
    voto31= input("inserisci il numero del voto: ")
    voto32= input("inserisci il numero del voto: ")
    voto33= input("inserisci il numero del voto: ")
    voto34= input("inserisci il numero del voto: ")
    voto35= input("inserisci il numero del voto: ")
    voto36= input("inserisci il numero del voto: ")
    voto37= input("inserisci il numero del voto: ")
    calcolo1= (int(voto1) + int(voto2) + int(voto3) + int(voto4) + int(voto5) + int(voto6) + int(voto7) + int(voto8) + int(voto9) + int(voto10) + int(voto11) + int(voto12) + int(voto13) + int(voto14) + int(voto15) + int(voto16) + int(voto17) + int(voto18) + int(voto19) + int(voto20) + int(voto21) + int(voto22) + int(voto23) + int(voto24) + int(voto25) + int(voto26) + int(voto27) + int(voto28) + int(voto29) + int(voto30) + int(voto31) + int(voto32) + int(voto33) + int(voto34) + int(voto35) + int(voto36) + int(voto37))
    calcolo2= (int(calcolo1) / int(totalevoti))
    print(calcolo2)
    input("Da Dario:")
if totalevoti == "38":
    voto1= input("inserisci il numero del voto: ")
    voto2= input("inserisci il numero del voto: ")
    voto3= input("inserisci il numero del voto: ")
    voto4= input("inserisci il numero del voto: ")
    voto5= input("inserisci il numero del voto: ")
    voto6= input("inserisci il numero del voto: ")
    voto7= input("inserisci il numero del voto: ")
    voto8= input("inserisci il numero del voto: ")
    voto9= input("inserisci il numero del voto: ")
    voto10= input("inserisci il numero del voto: ")
    voto11= input("inserisci il numero del voto: ")
    voto12= input("inserisci il numero del voto: ")
    voto13= input("inserisci il numero del voto: ")
    voto14= input("inserisci il numero del voto: ")
    voto15= input("inserisci il numero del voto: ")
    voto16= input("inserisci il numero del voto: ")
    voto17= input("inserisci il numero del voto: ")
    voto18= input("inserisci il numero del voto: ")
    voto19= input("inserisci il numero del voto: ")
    voto20= input("inserisci il numero del voto: ")
    voto21= input("inserisci il numero del voto: ")
    voto22= input("inserisci il numero del voto: ")
    voto23= input("inserisci il numero del voto: ")
    voto24= input("inserisci il numero del voto: ")
    voto25= input("inserisci il numero del voto: ")
    voto26= input("inserisci il numero del voto: ")
    voto27= input("inserisci il numero del voto: ")
    voto28= input("inserisci il numero del voto: ")
    voto29= input("inserisci il numero del voto: ")
    voto30= input("inserisci il numero del voto: ")
    voto31= input("inserisci il numero del voto: ")
    voto32= input("inserisci il numero del voto: ")
    voto33= input("inserisci il numero del voto: ")
    voto34= input("inserisci il numero del voto: ")
    voto35= input("inserisci il numero del voto: ")
    voto36= input("inserisci il numero del voto: ")
    voto37= input("inserisci il numero del voto: ")
    voto38= input("inserisci il numero del voto: ")
    calcolo1= (int(voto1) + int(voto2) + int(voto3) + int(voto4) + int(voto5) + int(voto6) + int(voto7) + int(voto8) + int(voto9) + int(voto10) + int(voto11) + int(voto12) + int(voto13) + int(voto14) + int(voto15) + int(voto16) + int(voto17) + int(voto18) + int(voto19) + int(voto20) + int(voto21) + int(voto22) + int(voto23) + int(voto24) + int(voto25) + int(voto26) + int(voto27) + int(voto28) + int(voto29) + int(voto30) + int(voto31) + int(voto32) + int(voto33) + int(voto34) + int(voto35) + int(voto36) + int(voto37) + int(voto38))
    calcolo2= (int(calcolo1) / int(totalevoti))
    print(calcolo2)
    input("Da Dario:")
if totalevoti == "39":
    voto1= input("inserisci il numero del voto: ")
    voto2= input("inserisci il numero del voto: ")
    voto3= input("inserisci il numero del voto: ")
    voto4= input("inserisci il numero del voto: ")
    voto5= input("inserisci il numero del voto: ")
    voto6= input("inserisci il numero del voto: ")
    voto7= input("inserisci il numero del voto: ")
    voto8= input("inserisci il numero del voto: ")
    voto9= input("inserisci il numero del voto: ")
    voto10= input("inserisci il numero del voto: ")
    voto11= input("inserisci il numero del voto: ")
    voto12= input("inserisci il numero del voto: ")
    voto13= input("inserisci il numero del voto: ")
    voto14= input("inserisci il numero del voto: ")
    voto15= input("inserisci il numero del voto: ")
    voto16= input("inserisci il numero del voto: ")
    voto17= input("inserisci il numero del voto: ")
    voto18= input("inserisci il numero del voto: ")
    voto19= input("inserisci il numero del voto: ")
    voto20= input("inserisci il numero del voto: ")
    voto21= input("inserisci il numero del voto: ")
    voto22= input("inserisci il numero del voto: ")
    voto23= input("inserisci il numero del voto: ")
    voto24= input("inserisci il numero del voto: ")
    voto25= input("inserisci il numero del voto: ")
    voto26= input("inserisci il numero del voto: ")
    voto27= input("inserisci il numero del voto: ")
    voto28= input("inserisci il numero del voto: ")
    voto29= input("inserisci il numero del voto: ")
    voto30= input("inserisci il numero del voto: ")
    voto31= input("inserisci il numero del voto: ")
    voto32= input("inserisci il numero del voto: ")
    voto33= input("inserisci il numero del voto: ")
    voto34= input("inserisci il numero del voto: ")
    voto35= input("inserisci il numero del voto: ")
    voto36= input("inserisci il numero del voto: ")
    voto37= input("inserisci il numero del voto: ")
    voto38= input("inserisci il numero del voto: ")
    voto39= input("inserisci il numero del voto: ")
    calcolo1= (int(voto1) + int(voto2) + int(voto3) + int(voto4) + int(voto5) + int(voto6) + int(voto7) + int(voto8) + int(voto9) + int(voto10) + int(voto11) + int(voto12) + int(voto13) + int(voto14) + int(voto15) + int(voto16) + int(voto17) + int(voto18) + int(voto19) + int(voto20) + int(voto21) + int(voto22) + int(voto23) + int(voto24) + int(voto25) + int(voto26) + int(voto27) + int(voto28) + int(voto29) + int(voto30) + int(voto31) + int(voto32) + int(voto33) + int(voto34) + int(voto35) + int(voto36) + int(voto37) + int(voto38) + int(voto39))
    calcolo2= (int(calcolo1) / int(totalevoti))
    print(calcolo2)
    input("Da Dario:")
if totalevoti == "39":
    voto1= input("inserisci il numero del voto: ")
    voto2= input("inserisci il numero del voto: ")
    voto3= input("inserisci il numero del voto: ")
    voto4= input("inserisci il numero del voto: ")
    voto5= input("inserisci il numero del voto: ")
    voto6= input("inserisci il numero del voto: ")
    voto7= input("inserisci il numero del voto: ")
    voto8= input("inserisci il numero del voto: ")
    voto9= input("inserisci il numero del voto: ")
    voto10= input("inserisci il numero del voto: ")
    voto11= input("inserisci il numero del voto: ")
    voto12= input("inserisci il numero del voto: ")
    voto13= input("inserisci il numero del voto: ")
    voto14= input("inserisci il numero del voto: ")
    voto15= input("inserisci il numero del voto: ")
    voto16= input("inserisci il numero del voto: ")
    voto17= input("inserisci il numero del voto: ")
    voto18= input("inserisci il numero del voto: ")
    voto19= input("inserisci il numero del voto: ")
    voto20= input("inserisci il numero del voto: ")
    voto21= input("inserisci il numero del voto: ")
    voto22= input("inserisci il numero del voto: ")
    voto23= input("inserisci il numero del voto: ")
    voto24= input("inserisci il numero del voto: ")
    voto25= input("inserisci il numero del voto: ")
    voto26= input("inserisci il numero del voto: ")
    voto27= input("inserisci il numero del voto: ")
    voto28= input("inserisci il numero del voto: ")
    voto29= input("inserisci il numero del voto: ")
    voto30= input("inserisci il numero del voto: ")
    voto31= input("inserisci il numero del voto: ")
    voto32= input("inserisci il numero del voto: ")
    voto33= input("inserisci il numero del voto: ")
    voto34= input("inserisci il numero del voto: ")
    voto35= input("inserisci il numero del voto: ")
    voto36= input("inserisci il numero del voto: ")
    voto37= input("inserisci il numero del voto: ")
    voto38= input("inserisci il numero del voto: ")
    voto39= input("inserisci il numero del voto: ")
    calcolo1= (int(voto1) + int(voto2) + int(voto3) + int(voto4) + int(voto5) + int(voto6) + int(voto7) + int(voto8) + int(voto9) + int(voto10) + int(voto11) + int(voto12) + int(voto13) + int(voto14) + int(voto15) + int(voto16) + int(voto17) + int(voto18) + int(voto19) + int(voto20) + int(voto21) + int(voto22) + int(voto23) + int(voto24) + int(voto25) + int(voto26) + int(voto27) + int(voto28) + int(voto29) + int(voto30) + int(voto31) + int(voto32) + int(voto33) + int(voto34) + int(voto35) + int(voto36) + int(voto37) + int(voto38) + int(voto39))
    calcolo2= (int(calcolo1) / int(totalevoti))
    print(calcolo2)
    input("Da Dario:")
if totalevoti == "40":
    voto1= input("inserisci il numero del voto: ")
    voto2= input("inserisci il numero del voto: ")
    voto3= input("inserisci il numero del voto: ")
    voto4= input("inserisci il numero del voto: ")
    voto5= input("inserisci il numero del voto: ")
    voto6= input("inserisci il numero del voto: ")
    voto7= input("inserisci il numero del voto: ")
    voto8= input("inserisci il numero del voto: ")
    voto9= input("inserisci il numero del voto: ")
    voto10= input("inserisci il numero del voto: ")
    voto11= input("inserisci il numero del voto: ")
    voto12= input("inserisci il numero del voto: ")
    voto13= input("inserisci il numero del voto: ")
    voto14= input("inserisci il numero del voto: ")
    voto15= input("inserisci il numero del voto: ")
    voto16= input("inserisci il numero del voto: ")
    voto17= input("inserisci il numero del voto: ")
    voto18= input("inserisci il numero del voto: ")
    voto19= input("inserisci il numero del voto: ")
    voto20= input("inserisci il numero del voto: ")
    voto21= input("inserisci il numero del voto: ")
    voto22= input("inserisci il numero del voto: ")
    voto23= input("inserisci il numero del voto: ")
    voto24= input("inserisci il numero del voto: ")
    voto25= input("inserisci il numero del voto: ")
    voto26= input("inserisci il numero del voto: ")
    voto27= input("inserisci il numero del voto: ")
    voto28= input("inserisci il numero del voto: ")
    voto29= input("inserisci il numero del voto: ")
    voto30= input("inserisci il numero del voto: ")
    voto31= input("inserisci il numero del voto: ")
    voto32= input("inserisci il numero del voto: ")
    voto33= input("inserisci il numero del voto: ")
    voto34= input("inserisci il numero del voto: ")
    voto35= input("inserisci il numero del voto: ")
    voto36= input("inserisci il numero del voto: ")
    voto37= input("inserisci il numero del voto: ")
    voto38= input("inserisci il numero del voto: ")
    voto39= input("inserisci il numero del voto: ")
    voto40= input("inserisci il numero del voto: ")
    calcolo1= (int(voto1) + int(voto2) + int(voto3) + int(voto4) + int(voto5) + int(voto6) + int(voto7) + int(voto8) + int(voto9) + int(voto10) + int(voto11) + int(voto12) + int(voto13) + int(voto14) + int(voto15) + int(voto16) + int(voto17) + int(voto18) + int(voto19) + int(voto20) + int(voto21) + int(voto22) + int(voto23) + int(voto24) + int(voto25) + int(voto26) + int(voto27) + int(voto28) + int(voto29) + int(voto30) + int(voto31) + int(voto32) + int(voto33) + int(voto34) + int(voto35) + int(voto36) + int(voto37) + int(voto38) + int(voto39) + int(voto40))
    calcolo2= (int(calcolo1) / int(totalevoti))
    print(calcolo2)
    input("Da Dario:")
if totalevoti == "41":
    voto1= input("inserisci il numero del voto: ")
    voto2= input("inserisci il numero del voto: ")
    voto3= input("inserisci il numero del voto: ")
    voto4= input("inserisci il numero del voto: ")
    voto5= input("inserisci il numero del voto: ")
    voto6= input("inserisci il numero del voto: ")
    voto7= input("inserisci il numero del voto: ")
    voto8= input("inserisci il numero del voto: ")
    voto9= input("inserisci il numero del voto: ")
    voto10= input("inserisci il numero del voto: ")
    voto11= input("inserisci il numero del voto: ")
    voto12= input("inserisci il numero del voto: ")
    voto13= input("inserisci il numero del voto: ")
    voto14= input("inserisci il numero del voto: ")
    voto15= input("inserisci il numero del voto: ")
    voto16= input("inserisci il numero del voto: ")
    voto17= input("inserisci il numero del voto: ")
    voto18= input("inserisci il numero del voto: ")
    voto19= input("inserisci il numero del voto: ")
    voto20= input("inserisci il numero del voto: ")
    voto21= input("inserisci il numero del voto: ")
    voto22= input("inserisci il numero del voto: ")
    voto23= input("inserisci il numero del voto: ")
    voto24= input("inserisci il numero del voto: ")
    voto25= input("inserisci il numero del voto: ")
    voto26= input("inserisci il numero del voto: ")
    voto27= input("inserisci il numero del voto: ")
    voto28= input("inserisci il numero del voto: ")
    voto29= input("inserisci il numero del voto: ")
    voto30= input("inserisci il numero del voto: ")
    voto31= input("inserisci il numero del voto: ")
    voto32= input("inserisci il numero del voto: ")
    voto33= input("inserisci il numero del voto: ")
    voto34= input("inserisci il numero del voto: ")
    voto35= input("inserisci il numero del voto: ")
    voto36= input("inserisci il numero del voto: ")
    voto37= input("inserisci il numero del voto: ")
    voto38= input("inserisci il numero del voto: ")
    voto39= input("inserisci il numero del voto: ")
    voto40= input("inserisci il numero del voto: ")
    voto41= input("inserisci il numero del voto: ")
    calcolo1= (int(voto1) + int(voto2) + int(voto3) + int(voto4) + int(voto5) + int(voto6) + int(voto7) + int(voto8) + int(voto9) + int(voto10) + int(voto11) + int(voto12) + int(voto13) + int(voto14) + int(voto15) + int(voto16) + int(voto17) + int(voto18) + int(voto19) + int(voto20) + int(voto21) + int(voto22) + int(voto23) + int(voto24) + int(voto25) + int(voto26) + int(voto27) + int(voto28) + int(voto29) + int(voto30) + int(voto31) + int(voto32) + int(voto33) + int(voto34) + int(voto35) + int(voto36) + int(voto37) + int(voto38) + int(voto39) + int(voto40) + int(voto41))
    calcolo2= (int(calcolo1) / int(totalevoti))
    print(calcolo2)
    input("Da Dario:")
if totalevoti == "42":
    voto1= input("inserisci il numero del voto: ")
    voto2= input("inserisci il numero del voto: ")
    voto3= input("inserisci il numero del voto: ")
    voto4= input("inserisci il numero del voto: ")
    voto5= input("inserisci il numero del voto: ")
    voto6= input("inserisci il numero del voto: ")
    voto7= input("inserisci il numero del voto: ")
    voto8= input("inserisci il numero del voto: ")
    voto9= input("inserisci il numero del voto: ")
    voto10= input("inserisci il numero del voto: ")
    voto11= input("inserisci il numero del voto: ")
    voto12= input("inserisci il numero del voto: ")
    voto13= input("inserisci il numero del voto: ")
    voto14= input("inserisci il numero del voto: ")
    voto15= input("inserisci il numero del voto: ")
    voto16= input("inserisci il numero del voto: ")
    voto17= input("inserisci il numero del voto: ")
    voto18= input("inserisci il numero del voto: ")
    voto19= input("inserisci il numero del voto: ")
    voto20= input("inserisci il numero del voto: ")
    voto21= input("inserisci il numero del voto: ")
    voto22= input("inserisci il numero del voto: ")
    voto23= input("inserisci il numero del voto: ")
    voto24= input("inserisci il numero del voto: ")
    voto25= input("inserisci il numero del voto: ")
    voto26= input("inserisci il numero del voto: ")
    voto27= input("inserisci il numero del voto: ")
    voto28= input("inserisci il numero del voto: ")
    voto29= input("inserisci il numero del voto: ")
    voto30= input("inserisci il numero del voto: ")
    voto31= input("inserisci il numero del voto: ")
    voto32= input("inserisci il numero del voto: ")
    voto33= input("inserisci il numero del voto: ")
    voto34= input("inserisci il numero del voto: ")
    voto35= input("inserisci il numero del voto: ")
    voto36= input("inserisci il numero del voto: ")
    voto37= input("inserisci il numero del voto: ")
    voto38= input("inserisci il numero del voto: ")
    voto39= input("inserisci il numero del voto: ")
    voto40= input("inserisci il numero del voto: ")
    voto41= input("inserisci il numero del voto: ")
    voto42= input("inserisci il numero del voto: ")
    calcolo1= (int(voto1) + int(voto2) + int(voto3) + int(voto4) + int(voto5) + int(voto6) + int(voto7) + int(voto8) + int(voto9) + int(voto10) + int(voto11) + int(voto12) + int(voto13) + int(voto14) + int(voto15) + int(voto16) + int(voto17) + int(voto18) + int(voto19) + int(voto20) + int(voto21) + int(voto22) + int(voto23) + int(voto24) + int(voto25) + int(voto26) + int(voto27) + int(voto28) + int(voto29) + int(voto30) + int(voto31) + int(voto32) + int(voto33) + int(voto34) + int(voto35) + int(voto36) + int(voto37) + int(voto38) + int(voto39) + int(voto40) + int(voto41) + int(voto42))
    calcolo2= (int(calcolo1) / int(totalevoti))
    print(calcolo2)
    input("Da Dario:")
if totalevoti == "43":
    voto1= input("inserisci il numero del voto: ")
    voto2= input("inserisci il numero del voto: ")
    voto3= input("inserisci il numero del voto: ")
    voto4= input("inserisci il numero del voto: ")
    voto5= input("inserisci il numero del voto: ")
    voto6= input("inserisci il numero del voto: ")
    voto7= input("inserisci il numero del voto: ")
    voto8= input("inserisci il numero del voto: ")
    voto9= input("inserisci il numero del voto: ")
    voto10= input("inserisci il numero del voto: ")
    voto11= input("inserisci il numero del voto: ")
    voto12= input("inserisci il numero del voto: ")
    voto13= input("inserisci il numero del voto: ")
    voto14= input("inserisci il numero del voto: ")
    voto15= input("inserisci il numero del voto: ")
    voto16= input("inserisci il numero del voto: ")
    voto17= input("inserisci il numero del voto: ")
    voto18= input("inserisci il numero del voto: ")
    voto19= input("inserisci il numero del voto: ")
    voto20= input("inserisci il numero del voto: ")
    voto21= input("inserisci il numero del voto: ")
    voto22= input("inserisci il numero del voto: ")
    voto23= input("inserisci il numero del voto: ")
    voto24= input("inserisci il numero del voto: ")
    voto25= input("inserisci il numero del voto: ")
    voto26= input("inserisci il numero del voto: ")
    voto27= input("inserisci il numero del voto: ")
    voto28= input("inserisci il numero del voto: ")
    voto29= input("inserisci il numero del voto: ")
    voto30= input("inserisci il numero del voto: ")
    voto31= input("inserisci il numero del voto: ")
    voto32= input("inserisci il numero del voto: ")
    voto33= input("inserisci il numero del voto: ")
    voto34= input("inserisci il numero del voto: ")
    voto35= input("inserisci il numero del voto: ")
    voto36= input("inserisci il numero del voto: ")
    voto37= input("inserisci il numero del voto: ")
    voto38= input("inserisci il numero del voto: ")
    voto39= input("inserisci il numero del voto: ")
    voto40= input("inserisci il numero del voto: ")
    voto41= input("inserisci il numero del voto: ")
    voto42= input("inserisci il numero del voto: ")
    voto43= input("inserisci il numero del voto: ")
    calcolo1= (int(voto1) + int(voto2) + int(voto3) + int(voto4) + int(voto5) + int(voto6) + int(voto7) + int(voto8) + int(voto9) + int(voto10) + int(voto11) + int(voto12) + int(voto13) + int(voto14) + int(voto15) + int(voto16) + int(voto17) + int(voto18) + int(voto19) + int(voto20) + int(voto21) + int(voto22) + int(voto23) + int(voto24) + int(voto25) + int(voto26) + int(voto27) + int(voto28) + int(voto29) + int(voto30) + int(voto31) + int(voto32) + int(voto33) + int(voto34) + int(voto35) + int(voto36) + int(voto37) + int(voto38) + int(voto39) + int(voto40) + int(voto41) + int(voto42) + int(voto43))
    calcolo2= (int(calcolo1) / int(totalevoti))
    print(calcolo2)
    input("Da Dario:")
if totalevoti == "44":
    voto1= input("inserisci il numero del voto: ")
    voto2= input("inserisci il numero del voto: ")
    voto3= input("inserisci il numero del voto: ")
    voto4= input("inserisci il numero del voto: ")
    voto5= input("inserisci il numero del voto: ")
    voto6= input("inserisci il numero del voto: ")
    voto7= input("inserisci il numero del voto: ")
    voto8= input("inserisci il numero del voto: ")
    voto9= input("inserisci il numero del voto: ")
    voto10= input("inserisci il numero del voto: ")
    voto11= input("inserisci il numero del voto: ")
    voto12= input("inserisci il numero del voto: ")
    voto13= input("inserisci il numero del voto: ")
    voto14= input("inserisci il numero del voto: ")
    voto15= input("inserisci il numero del voto: ")
    voto16= input("inserisci il numero del voto: ")
    voto17= input("inserisci il numero del voto: ")
    voto18= input("inserisci il numero del voto: ")
    voto19= input("inserisci il numero del voto: ")
    voto20= input("inserisci il numero del voto: ")
    voto21= input("inserisci il numero del voto: ")
    voto22= input("inserisci il numero del voto: ")
    voto23= input("inserisci il numero del voto: ")
    voto24= input("inserisci il numero del voto: ")
    voto25= input("inserisci il numero del voto: ")
    voto26= input("inserisci il numero del voto: ")
    voto27= input("inserisci il numero del voto: ")
    voto28= input("inserisci il numero del voto: ")
    voto29= input("inserisci il numero del voto: ")
    voto30= input("inserisci il numero del voto: ")
    voto31= input("inserisci il numero del voto: ")
    voto32= input("inserisci il numero del voto: ")
    voto33= input("inserisci il numero del voto: ")
    voto34= input("inserisci il numero del voto: ")
    voto35= input("inserisci il numero del voto: ")
    voto36= input("inserisci il numero del voto: ")
    voto37= input("inserisci il numero del voto: ")
    voto38= input("inserisci il numero del voto: ")
    voto39= input("inserisci il numero del voto: ")
    voto40= input("inserisci il numero del voto: ")
    voto41= input("inserisci il numero del voto: ")
    voto42= input("inserisci il numero del voto: ")
    voto43= input("inserisci il numero del voto: ")
    voto44= input("inserisci il numero del voto: ")
    calcolo1= (int(voto1) + int(voto2) + int(voto3) + int(voto4) + int(voto5) + int(voto6) + int(voto7) + int(voto8) + int(voto9) + int(voto10) + int(voto11) + int(voto12) + int(voto13) + int(voto14) + int(voto15) + int(voto16) + int(voto17) + int(voto18) + int(voto19) + int(voto20) + int(voto21) + int(voto22) + int(voto23) + int(voto24) + int(voto25) + int(voto26) + int(voto27) + int(voto28) + int(voto29) + int(voto30) + int(voto31) + int(voto32) + int(voto33) + int(voto34) + int(voto35) + int(voto36) + int(voto37) + int(voto38) + int(voto39) + int(voto40) + int(voto41) + int(voto42) + int(voto43) + int(voto44))
    calcolo2= (int(calcolo1) / int(totalevoti))
    print(calcolo2)
    input("Da Dario:")
if totalevoti == "45":
    voto1= input("inserisci il numero del voto: ")
    voto2= input("inserisci il numero del voto: ")
    voto3= input("inserisci il numero del voto: ")
    voto4= input("inserisci il numero del voto: ")
    voto5= input("inserisci il numero del voto: ")
    voto6= input("inserisci il numero del voto: ")
    voto7= input("inserisci il numero del voto: ")
    voto8= input("inserisci il numero del voto: ")
    voto9= input("inserisci il numero del voto: ")
    voto10= input("inserisci il numero del voto: ")
    voto11= input("inserisci il numero del voto: ")
    voto12= input("inserisci il numero del voto: ")
    voto13= input("inserisci il numero del voto: ")
    voto14= input("inserisci il numero del voto: ")
    voto15= input("inserisci il numero del voto: ")
    voto16= input("inserisci il numero del voto: ")
    voto17= input("inserisci il numero del voto: ")
    voto18= input("inserisci il numero del voto: ")
    voto19= input("inserisci il numero del voto: ")
    voto20= input("inserisci il numero del voto: ")
    voto21= input("inserisci il numero del voto: ")
    voto22= input("inserisci il numero del voto: ")
    voto23= input("inserisci il numero del voto: ")
    voto24= input("inserisci il numero del voto: ")
    voto25= input("inserisci il numero del voto: ")
    voto26= input("inserisci il numero del voto: ")
    voto27= input("inserisci il numero del voto: ")
    voto28= input("inserisci il numero del voto: ")
    voto29= input("inserisci il numero del voto: ")
    voto30= input("inserisci il numero del voto: ")
    voto31= input("inserisci il numero del voto: ")
    voto32= input("inserisci il numero del voto: ")
    voto33= input("inserisci il numero del voto: ")
    voto34= input("inserisci il numero del voto: ")
    voto35= input("inserisci il numero del voto: ")
    voto36= input("inserisci il numero del voto: ")
    voto37= input("inserisci il numero del voto: ")
    voto38= input("inserisci il numero del voto: ")
    voto39= input("inserisci il numero del voto: ")
    voto40= input("inserisci il numero del voto: ")
    voto41= input("inserisci il numero del voto: ")
    voto42= input("inserisci il numero del voto: ")
    voto43= input("inserisci il numero del voto: ")
    voto44= input("inserisci il numero del voto: ")
    voto45= input("inserisci il numero del voto: ")
    calcolo1= (int(voto1) + int(voto2) + int(voto3) + int(voto4) + int(voto5) + int(voto6) + int(voto7) + int(voto8) + int(voto9) + int(voto10) + int(voto11) + int(voto12) + int(voto13) + int(voto14) + int(voto15) + int(voto16) + int(voto17) + int(voto18) + int(voto19) + int(voto20) + int(voto21) + int(voto22) + int(voto23) + int(voto24) + int(voto25) + int(voto26) + int(voto27) + int(voto28) + int(voto29) + int(voto30) + int(voto31) + int(voto32) + int(voto33) + int(voto34) + int(voto35) + int(voto36) + int(voto37) + int(voto38) + int(voto39) + int(voto40) + int(voto41) + int(voto42) + int(voto43) + int(voto44) + int(voto45))
    calcolo2= (int(calcolo1) / int(totalevoti))
    print(calcolo2)
    input("Da Dario:")
if totalevoti == "46":
    voto1= input("inserisci il numero del voto: ")
    voto2= input("inserisci il numero del voto: ")
    voto3= input("inserisci il numero del voto: ")
    voto4= input("inserisci il numero del voto: ")
    voto5= input("inserisci il numero del voto: ")
    voto6= input("inserisci il numero del voto: ")
    voto7= input("inserisci il numero del voto: ")
    voto8= input("inserisci il numero del voto: ")
    voto9= input("inserisci il numero del voto: ")
    voto10= input("inserisci il numero del voto: ")
    voto11= input("inserisci il numero del voto: ")
    voto12= input("inserisci il numero del voto: ")
    voto13= input("inserisci il numero del voto: ")
    voto14= input("inserisci il numero del voto: ")
    voto15= input("inserisci il numero del voto: ")
    voto16= input("inserisci il numero del voto: ")
    voto17= input("inserisci il numero del voto: ")
    voto18= input("inserisci il numero del voto: ")
    voto19= input("inserisci il numero del voto: ")
    voto20= input("inserisci il numero del voto: ")
    voto21= input("inserisci il numero del voto: ")
    voto22= input("inserisci il numero del voto: ")
    voto23= input("inserisci il numero del voto: ")
    voto24= input("inserisci il numero del voto: ")
    voto25= input("inserisci il numero del voto: ")
    voto26= input("inserisci il numero del voto: ")
    voto27= input("inserisci il numero del voto: ")
    voto28= input("inserisci il numero del voto: ")
    voto29= input("inserisci il numero del voto: ")
    voto30= input("inserisci il numero del voto: ")
    voto31= input("inserisci il numero del voto: ")
    voto32= input("inserisci il numero del voto: ")
    voto33= input("inserisci il numero del voto: ")
    voto34= input("inserisci il numero del voto: ")
    voto35= input("inserisci il numero del voto: ")
    voto36= input("inserisci il numero del voto: ")
    voto37= input("inserisci il numero del voto: ")
    voto38= input("inserisci il numero del voto: ")
    voto39= input("inserisci il numero del voto: ")
    voto40= input("inserisci il numero del voto: ")
    voto41= input("inserisci il numero del voto: ")
    voto42= input("inserisci il numero del voto: ")
    voto43= input("inserisci il numero del voto: ")
    voto44= input("inserisci il numero del voto: ")
    voto45= input("inserisci il numero del voto: ")
    voto46= input("inserisci il numero del voto: ")
    calcolo1= (int(voto1) + int(voto2) + int(voto3) + int(voto4) + int(voto5) + int(voto6) + int(voto7) + int(voto8) + int(voto9) + int(voto10) + int(voto11) + int(voto12) + int(voto13) + int(voto14) + int(voto15) + int(voto16) + int(voto17) + int(voto18) + int(voto19) + int(voto20) + int(voto21) + int(voto22) + int(voto23) + int(voto24) + int(voto25) + int(voto26) + int(voto27) + int(voto28) + int(voto29) + int(voto30) + int(voto31) + int(voto32) + int(voto33) + int(voto34) + int(voto35) + int(voto36) + int(voto37) + int(voto38) + int(voto39) + int(voto40) + int(voto41) + int(voto42) + int(voto43) + int(voto44) + int(voto45) + int(voto46))
    calcolo2= (int(calcolo1) / int(totalevoti))
    print(calcolo2)
    input("Da Dario:")
if totalevoti == "47":
    voto1= input("inserisci il numero del voto: ")
    voto2= input("inserisci il numero del voto: ")
    voto3= input("inserisci il numero del voto: ")
    voto4= input("inserisci il numero del voto: ")
    voto5= input("inserisci il numero del voto: ")
    voto6= input("inserisci il numero del voto: ")
    voto7= input("inserisci il numero del voto: ")
    voto8= input("inserisci il numero del voto: ")
    voto9= input("inserisci il numero del voto: ")
    voto10= input("inserisci il numero del voto: ")
    voto11= input("inserisci il numero del voto: ")
    voto12= input("inserisci il numero del voto: ")
    voto13= input("inserisci il numero del voto: ")
    voto14= input("inserisci il numero del voto: ")
    voto15= input("inserisci il numero del voto: ")
    voto16= input("inserisci il numero del voto: ")
    voto17= input("inserisci il numero del voto: ")
    voto18= input("inserisci il numero del voto: ")
    voto19= input("inserisci il numero del voto: ")
    voto20= input("inserisci il numero del voto: ")
    voto21= input("inserisci il numero del voto: ")
    voto22= input("inserisci il numero del voto: ")
    voto23= input("inserisci il numero del voto: ")
    voto24= input("inserisci il numero del voto: ")
    voto25= input("inserisci il numero del voto: ")
    voto26= input("inserisci il numero del voto: ")
    voto27= input("inserisci il numero del voto: ")
    voto28= input("inserisci il numero del voto: ")
    voto29= input("inserisci il numero del voto: ")
    voto30= input("inserisci il numero del voto: ")
    voto31= input("inserisci il numero del voto: ")
    voto32= input("inserisci il numero del voto: ")
    voto33= input("inserisci il numero del voto: ")
    voto34= input("inserisci il numero del voto: ")
    voto35= input("inserisci il numero del voto: ")
    voto36= input("inserisci il numero del voto: ")
    voto37= input("inserisci il numero del voto: ")
    voto38= input("inserisci il numero del voto: ")
    voto39= input("inserisci il numero del voto: ")
    voto40= input("inserisci il numero del voto: ")
    voto41= input("inserisci il numero del voto: ")
    voto42= input("inserisci il numero del voto: ")
    voto43= input("inserisci il numero del voto: ")
    voto44= input("inserisci il numero del voto: ")
    voto45= input("inserisci il numero del voto: ")
    voto46= input("inserisci il numero del voto: ")
    voto47= input("inserisci il numero del voto: ")
    calcolo1= (int(voto1) + int(voto2) + int(voto3) + int(voto4) + int(voto5) + int(voto6) + int(voto7) + int(voto8) + int(voto9) + int(voto10) + int(voto11) + int(voto12) + int(voto13) + int(voto14) + int(voto15) + int(voto16) + int(voto17) + int(voto18) + int(voto19) + int(voto20) + int(voto21) + int(voto22) + int(voto23) + int(voto24) + int(voto25) + int(voto26) + int(voto27) + int(voto28) + int(voto29) + int(voto30) + int(voto31) + int(voto32) + int(voto33) + int(voto34) + int(voto35) + int(voto36) + int(voto37) + int(voto38) + int(voto39) + int(voto40) + int(voto41) + int(voto42) + int(voto43) + int(voto44) + int(voto45) + int(voto46) + int(voto47))
    calcolo2= (int(calcolo1) / int(totalevoti))
    print(calcolo2)
    input("Da Dario:")
if totalevoti == "48":
    voto1= input("inserisci il numero del voto: ")
    voto2= input("inserisci il numero del voto: ")
    voto3= input("inserisci il numero del voto: ")
    voto4= input("inserisci il numero del voto: ")
    voto5= input("inserisci il numero del voto: ")
    voto6= input("inserisci il numero del voto: ")
    voto7= input("inserisci il numero del voto: ")
    voto8= input("inserisci il numero del voto: ")
    voto9= input("inserisci il numero del voto: ")
    voto10= input("inserisci il numero del voto: ")
    voto11= input("inserisci il numero del voto: ")
    voto12= input("inserisci il numero del voto: ")
    voto13= input("inserisci il numero del voto: ")
    voto14= input("inserisci il numero del voto: ")
    voto15= input("inserisci il numero del voto: ")
    voto16= input("inserisci il numero del voto: ")
    voto17= input("inserisci il numero del voto: ")
    voto18= input("inserisci il numero del voto: ")
    voto19= input("inserisci il numero del voto: ")
    voto20= input("inserisci il numero del voto: ")
    voto21= input("inserisci il numero del voto: ")
    voto22= input("inserisci il numero del voto: ")
    voto23= input("inserisci il numero del voto: ")
    voto24= input("inserisci il numero del voto: ")
    voto25= input("inserisci il numero del voto: ")
    voto26= input("inserisci il numero del voto: ")
    voto27= input("inserisci il numero del voto: ")
    voto28= input("inserisci il numero del voto: ")
    voto29= input("inserisci il numero del voto: ")
    voto30= input("inserisci il numero del voto: ")
    voto31= input("inserisci il numero del voto: ")
    voto32= input("inserisci il numero del voto: ")
    voto33= input("inserisci il numero del voto: ")
    voto34= input("inserisci il numero del voto: ")
    voto35= input("inserisci il numero del voto: ")
    voto36= input("inserisci il numero del voto: ")
    voto37= input("inserisci il numero del voto: ")
    voto38= input("inserisci il numero del voto: ")
    voto39= input("inserisci il numero del voto: ")
    voto40= input("inserisci il numero del voto: ")
    voto41= input("inserisci il numero del voto: ")
    voto42= input("inserisci il numero del voto: ")
    voto43= input("inserisci il numero del voto: ")
    voto44= input("inserisci il numero del voto: ")
    voto45= input("inserisci il numero del voto: ")
    voto46= input("inserisci il numero del voto: ")
    voto47= input("inserisci il numero del voto: ")
    voto48= input("inserisci il numero del voto: ")
    calcolo1= (int(voto1) + int(voto2) + int(voto3) + int(voto4) + int(voto5) + int(voto6) + int(voto7) + int(voto8) + int(voto9) + int(voto10) + int(voto11) + int(voto12) + int(voto13) + int(voto14) + int(voto15) + int(voto16) + int(voto17) + int(voto18) + int(voto19) + int(voto20) + int(voto21) + int(voto22) + int(voto23) + int(voto24) + int(voto25) + int(voto26) + int(voto27) + int(voto28) + int(voto29) + int(voto30) + int(voto31) + int(voto32) + int(voto33) + int(voto34) + int(voto35) + int(voto36) + int(voto37) + int(voto38) + int(voto39) + int(voto40) + int(voto41) + int(voto42) + int(voto43) + int(voto44) + int(voto45) + int(voto46) + int(voto47) + int(voto48))
    calcolo2= (int(calcolo1) / int(totalevoti))
    print(calcolo2)
    input("Da Dario:")
if totalevoti == "49":
    voto1= input("inserisci il numero del voto: ")
    voto2= input("inserisci il numero del voto: ")
    voto3= input("inserisci il numero del voto: ")
    voto4= input("inserisci il numero del voto: ")
    voto5= input("inserisci il numero del voto: ")
    voto6= input("inserisci il numero del voto: ")
    voto7= input("inserisci il numero del voto: ")
    voto8= input("inserisci il numero del voto: ")
    voto9= input("inserisci il numero del voto: ")
    voto10= input("inserisci il numero del voto: ")
    voto11= input("inserisci il numero del voto: ")
    voto12= input("inserisci il numero del voto: ")
    voto13= input("inserisci il numero del voto: ")
    voto14= input("inserisci il numero del voto: ")
    voto15= input("inserisci il numero del voto: ")
    voto16= input("inserisci il numero del voto: ")
    voto17= input("inserisci il numero del voto: ")
    voto18= input("inserisci il numero del voto: ")
    voto19= input("inserisci il numero del voto: ")
    voto20= input("inserisci il numero del voto: ")
    voto21= input("inserisci il numero del voto: ")
    voto22= input("inserisci il numero del voto: ")
    voto23= input("inserisci il numero del voto: ")
    voto24= input("inserisci il numero del voto: ")
    voto25= input("inserisci il numero del voto: ")
    voto26= input("inserisci il numero del voto: ")
    voto27= input("inserisci il numero del voto: ")
    voto28= input("inserisci il numero del voto: ")
    voto29= input("inserisci il numero del voto: ")
    voto30= input("inserisci il numero del voto: ")
    voto31= input("inserisci il numero del voto: ")
    voto32= input("inserisci il numero del voto: ")
    voto33= input("inserisci il numero del voto: ")
    voto34= input("inserisci il numero del voto: ")
    voto35= input("inserisci il numero del voto: ")
    voto36= input("inserisci il numero del voto: ")
    voto37= input("inserisci il numero del voto: ")
    voto38= input("inserisci il numero del voto: ")
    voto39= input("inserisci il numero del voto: ")
    voto40= input("inserisci il numero del voto: ")
    voto41= input("inserisci il numero del voto: ")
    voto42= input("inserisci il numero del voto: ")
    voto43= input("inserisci il numero del voto: ")
    voto44= input("inserisci il numero del voto: ")
    voto45= input("inserisci il numero del voto: ")
    voto46= input("inserisci il numero del voto: ")
    voto47= input("inserisci il numero del voto: ")
    voto48= input("inserisci il numero del voto: ")
    voto49= input("inserisci il numero del voto: ")
    calcolo1= (int(voto1) + int(voto2) + int(voto3) + int(voto4) + int(voto5) + int(voto6) + int(voto7) + int(voto8) + int(voto9) + int(voto10) + int(voto11) + int(voto12) + int(voto13) + int(voto14) + int(voto15) + int(voto16) + int(voto17) + int(voto18) + int(voto19) + int(voto20) + int(voto21) + int(voto22) + int(voto23) + int(voto24) + int(voto25) + int(voto26) + int(voto27) + int(voto28) + int(voto29) + int(voto30) + int(voto31) + int(voto32) + int(voto33) + int(voto34) + int(voto35) + int(voto36) + int(voto37) + int(voto38) + int(voto39) + int(voto40) + int(voto41) + int(voto42) + int(voto43) + int(voto44) + int(voto45) + int(voto46) + int(voto47) + int(voto48) + int(voto49))
    calcolo2= (int(calcolo1) / int(totalevoti))
    print(calcolo2)
    input("Da Dario:")
if totalevoti == "50":
    voto1= input("inserisci il numero del voto: ")
    voto2= input("inserisci il numero del voto: ")
    voto3= input("inserisci il numero del voto: ")
    voto4= input("inserisci il numero del voto: ")
    voto5= input("inserisci il numero del voto: ")
    voto6= input("inserisci il numero del voto: ")
    voto7= input("inserisci il numero del voto: ")
    voto8= input("inserisci il numero del voto: ")
    voto9= input("inserisci il numero del voto: ")
    voto10= input("inserisci il numero del voto: ")
    voto11= input("inserisci il numero del voto: ")
    voto12= input("inserisci il numero del voto: ")
    voto13= input("inserisci il numero del voto: ")
    voto14= input("inserisci il numero del voto: ")
    voto15= input("inserisci il numero del voto: ")
    voto16= input("inserisci il numero del voto: ")
    voto17= input("inserisci il numero del voto: ")
    voto18= input("inserisci il numero del voto: ")
    voto19= input("inserisci il numero del voto: ")
    voto20= input("inserisci il numero del voto: ")
    voto21= input("inserisci il numero del voto: ")
    voto22= input("inserisci il numero del voto: ")
    voto23= input("inserisci il numero del voto: ")
    voto24= input("inserisci il numero del voto: ")
    voto25= input("inserisci il numero del voto: ")
    voto26= input("inserisci il numero del voto: ")
    voto27= input("inserisci il numero del voto: ")
    voto28= input("inserisci il numero del voto: ")
    voto29= input("inserisci il numero del voto: ")
    voto30= input("inserisci il numero del voto: ")
    voto31= input("inserisci il numero del voto: ")
    voto32= input("inserisci il numero del voto: ")
    voto33= input("inserisci il numero del voto: ")
    voto34= input("inserisci il numero del voto: ")
    voto35= input("inserisci il numero del voto: ")
    voto36= input("inserisci il numero del voto: ")
    voto37= input("inserisci il numero del voto: ")
    voto38= input("inserisci il numero del voto: ")
    voto39= input("inserisci il numero del voto: ")
    voto40= input("inserisci il numero del voto: ")
    voto41= input("inserisci il numero del voto: ")
    voto42= input("inserisci il numero del voto: ")
    voto43= input("inserisci il numero del voto: ")
    voto44= input("inserisci il numero del voto: ")
    voto45= input("inserisci il numero del voto: ")
    voto46= input("inserisci il numero del voto: ")
    voto47= input("inserisci il numero del voto: ")
    voto48= input("inserisci il numero del voto: ")
    voto49= input("inserisci il numero del voto: ")
    voto50= input("inserisci il numero del voto: ")
    calcolo1= (int(voto1) + int(voto2) + int(voto3) + int(voto4) + int(voto5) + int(voto6) + int(voto7) + int(voto8) + int(voto9) + int(voto10) + int(voto11) + int(voto12) + int(voto13) + int(voto14) + int(voto15) + int(voto16) + int(voto17) + int(voto18) + int(voto19) + int(voto20) + int(voto21) + int(voto22) + int(voto23) + int(voto24) + int(voto25) + int(voto26) + int(voto27) + int(voto28) + int(voto29) + int(voto30) + int(voto31) + int(voto32) + int(voto33) + int(voto34) + int(voto35) + int(voto36) + int(voto37) + int(voto38) + int(voto39) + int(voto40) + int(voto41) + int(voto42) + int(voto43) + int(voto44) + int(voto45) + int(voto46) + int(voto47) + int(voto48) + int(voto49) + int(voto50))
    calcolo2= (int(calcolo1) / int(totalevoti))
    print(calcolo2)
    input("Da Dario:")